apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::646071784763:role/eksctl-eksctl-demo-nodegroup-ng-4-NodeInstanceRole-1JYQORKQYG92W
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::646071784763:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-23T19:36:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1854"
  uid: 3db60707-4c02-498c-8e6f-ce66c68d12ce
